import json

# Load existing templates_complete.json
with open('app/static/templates/templates_complete.json', 'r') as f:
    data = json.load(f)
existing = data['templates']
existing_ids = {t['id'] for t in existing}
print(f"Existing templates: {len(existing)}")

# Missing templates 006-021 (16 templates)
# We'll define them manually based on the data from generate_templates.py and create_new_templates.py
# Note: category for template_011 changed from 'reggae' to 'latin' to match dropdown
missing_templates = [
    {
        "id": "template_006",
        "name": "Tropical House Summer",
        "description": "Sunny tropical house with steel drums and beach vibes",
        "category": "electronic",
        "subcategory": "tropical",
        "prompt": "A sunny tropical house track with steel drum melodies, beachy vibes, and uplifting energy. Create a summer vacation atmosphere with bright synths, relaxed rhythms, and feel-good vocals. The track should evoke images of palm trees, ocean waves, and sunset parties. Include tropical percussion, catchy hooks, and a breezy arrangement that makes listeners feel like they're on a tropical island getaway.",
        "style": "tropical, house, summer, beachy, uplifting, sunny",
        "tags": ["electronic", "tropical", "house", "summer", "beachy", "uplifting", "happy"],
        "bpm": 115,
        "duration": "3:30",
        "instrumental": False,
        "difficulty": "intermediate",
        "popularity": 87,
        "author": "System",
        "created_at": "2024-01-12",
        "updated_at": "2024-01-12",
        "example_image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop",
        "metadata": {
            "model": "V5",
            "temperature": 0.8,
            "top_p": 0.95,
            "presence_penalty": 0.1,
            "frequency_penalty": 0.1
        }
    },
    {
        "id": "template_007",
        "name": "Psychedelic Rock Journey",
        "description": "Mind-bending psychedelic rock with swirling guitars and trippy effects",
        "category": "rock",
        "subcategory": "psychedelic",
        "prompt": "A psychedelic rock journey featuring swirling guitar effects, hypnotic rhythms, and mind-expanding soundscapes. Create a trippy, immersive experience with phaser-drenched guitars, organ drones, and experimental textures. The track should evolve through different sections, taking listeners on a sonic adventure through altered states of consciousness. Include improvisational elements, stereo panning effects, and a sense of cosmic exploration.",
        "style": "psychedelic, rock, trippy, experimental, immersive, cosmic",
        "tags": ["rock", "psychedelic", "experimental", "trippy", "guitar", "immersive"],
        "bpm": 100,
        "duration": "6:45",
        "instrumental": True,
        "difficulty": "advanced",
        "popularity": 82,
        "author": "System",
        "created_at": "2024-01-12",
        "updated_at": "2024-01-12",
        "example_image_url": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&h=300&fit=crop",
        "metadata": {
            "model": "V5",
            "temperature": 0.8,
            "top_p": 0.95,
            "presence_penalty": 0.1,
            "frequency_penalty": 0.1
        }
    },
    {
        "id": "template_008",
        "name": "Jazz Club Trio",
        "description": "Intimate jazz trio performance with piano, bass, and drums",
        "category": "jazz",
        "subcategory": "trio",
        "prompt": "An intimate jazz trio performance featuring piano, upright bass, and drums. Create a smoky club atmosphere with sophisticated harmonies, walking basslines, and tasteful drumming. The track should feature a standard jazz form with solos for each instrument, showcasing musical conversation and improvisational skill. Include swing feel, bluesy inflections, and the warm, organic sound of acoustic instruments in a cozy venue.",
        "style": "jazz, acoustic, intimate, sophisticated, swinging, bluesy",
        "tags": ["jazz", "acoustic", "trio", "intimate", "sophisticated", "improvisation"],
        "bpm": 140,
        "duration": "5:20",
        "instrumental": True,
        "difficulty": "advanced",
        "popularity": 85,
        "author": "System",
        "created_at": "2024-01-12",
        "updated_at": "2024-01-12",
        "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
        "metadata": {
            "model": "V5",
            "temperature": 0.8,
            "top_p": 0.95,
            "presence_penalty": 0.1,
            "frequency_penalty": 0.1
        }
    },
    {
        "id": "template_009",
        "name": "Future Bass Drop",
        "description": "Emotional future bass with huge drops and melodic supersaws",
        "category": "electronic",
        "subcategory": "futurebass",
        "prompt": "An emotional future bass track with huge drops, melodic supersaws, and heartfelt vocals. Create a balance between aggressive electronic production and emotional songwriting. The track should feature atmospheric verses, building tension, and explosive drops with intricate sound design. Include pitch-bent synths, vocal chops, and a sense of youthful energy mixed with melancholic beauty.",
        "style": "future bass, emotional, melodic, aggressive, atmospheric, drop",
        "tags": ["electronic", "future bass", "emotional", "melodic", "drop", "energetic"],
        "bpm": 150,
        "duration": "3:45",
        "instrumental": False,
        "difficulty": "intermediate",
        "popularity": 91,
        "author": "System",
        "created_at": "2024-01-12",
        "updated_at": "2024-01-12",
        "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
        "metadata": {
            "model": "V5",
            "temperature": 0.8,
            "top_p": 0.95,
            "presence_penalty": 0.1,
            "frequency_penalty": 0.1
        }
    },
    {
        "id": "template_010",
        "name": "Classical Piano Sonata",
        "description": "Elegant classical piano composition in sonata form",
        "category": "classical",
        "subcategory": "piano",
        "prompt": "An elegant classical piano sonata following traditional form and structure. Create a composition with clear thematic development, contrasting sections, and technical artistry. The track should demonstrate proper voice leading, harmonic progression, and dynamic expression. Include a memorable main theme, development section exploring different keys and textures, and a satisfying recapitulation. Capture the refined beauty of classical piano music with emotional depth and technical precision.",
        "style": "classical, piano, elegant, sophisticated, technical, emotional",
        "tags": ["classical", "piano", "elegant", "sophisticated", "technical", "emotional"],
        "bpm": 100,
        "duration": "7:30",
        "instrumental": True,
        "difficulty": "advanced",
        "popularity": 84,
        "author": "System",
        "created_at": "2024-01-12",
        "updated_at": "2024-01-12",
        "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
        "metadata": {
            "model": "V5",
            "temperature": 0.8,
            "top_p": 0.95,
            "presence_penalty": 0.1,
            "frequency_penalty": 0.1
        }
    },
    {
        "id": "template_011",
        "name": "Reggae Sunshine",
        "description": "Chilled reggae with positive vibes and laid-back groove",
        "category": "latin",
        "subcategory": "roots",
        "prompt": "A chilled reggae track with positive vibes, laid-back groove, and uplifting message. Create a sunny, relaxed atmosphere with off-beat guitar chops, walking basslines, and steady one-drop drum pattern. The track should feature soulful vocals about unity, love, and social consciousness. Include horn stabs, organ skanks, and that unmistakable reggae bounce that makes people sway and smile.",
        "style": "reggae, chilled, positive, laid-back, sunny, roots",
        "tags": ["reggae", "chilled", "positive", "laid-back", "sunny", "roots"],
        "bpm": 80,
        "duration": "4:10",
        "instrumental": False,
        "difficulty": "intermediate",
        "popularity": 86,
        "author": "System",
        "created_at": "2024-01-12",
        "updated_at": "2024-01-12",
        "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
        "metadata": {
            "model": "V5",
            "temperature": 0.8,
            "top_p": 0.95,
            "presence_penalty": 0.1,
            "frequency_penalty": 0.1
        }
    },
    {
        "id": "template_012",
        "name": "Hyperpop Glitchcore",
        "description": "Maximalist hyperpop with glitch effects and digital chaos",
        "category": "hyperpop",
        "subcategory": "glitch",
        "prompt": "A hyperpop track featuring glitch effects, digital chaos, and maximalist production. Create a sonic landscape of distorted vocals, crushed drums, and rainbow-bright synthesizers. The track should embody internet culture with TikTok-ready hooks, aggressive autotune, and chaotic breakdowns. Include hyper-compressed drums, pitch-shifted vocals, and video game sound effects that create a sense of digital overload and euphoric confusion.",
        "style": "hyperpop, glitch, digital, chaotic, maximalist, bright",
        "tags": ["hyperpop", "glitch", "digital", "chaotic", "maximalist", "bright", "internet"],
        "bpm": 160,
        "duration": "2:30",
        "instrumental": False,
        "difficulty": "intermediate",
        "popularity": 89,
        "author": "System",
        "created_at": "2024-01-24",
        "updated_at": "2024-01-24",
        "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
        "metadata": {"model": "V5", "temperature": 0.9, "top_p": 0.95, "presence_penalty": 0.2, "frequency_penalty": 0.1}
    },
    {
        "id": "template_013",
        "name": "Drill Atmosphere",
        "description": "Gritty UK drill with dark atmospheres and menacing bass",
        "category": "drill",
        "subcategory": "uk",
        "prompt": "A UK drill track with dark atmospheres, menacing 808 bass, and gritty realism. Create a cold, urban soundscape with sparse percussion, haunting melodies, and aggressive vocal delivery. The track should evoke late-night city streets, tension, and survival mentality. Include sliding 808s, trap-style hi-hats, and atmospheric pads that create a sense of unease and raw energy.",
        "style": "drill, dark, gritty, atmospheric, menacing, urban",
        "tags": ["drill", "dark", "gritty", "atmospheric", "menacing", "urban", "uk"],
        "bpm": 140,
        "duration": "3:15",
        "instrumental": True,
        "difficulty": "intermediate",
        "popularity": 87,
        "author": "System",
        "created_at": "2024-01-24",
        "updated_at": "2024-01-24",
        "example_image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop",
        "metadata": {"model": "V5", "temperature": 0.7, "top_p": 0.9, "presence_penalty": 0.1, "frequency_penalty": 0.1}
    },
    {
        "id": "template_014",
        "name": "Ambient Electronica",
        "description": "Ethereal ambient electronica with evolving textures and cosmic atmospheres",
        "category": "ambient",
        "subcategory": "electronica",
        "prompt": "An ambient electronica track with evolving textures, cosmic atmospheres, and subtle rhythmic pulses. Create a meditative yet digital soundscape that bridges organic warmth with synthetic precision. The track should feature slowly morphing pads, granular synthesis, and gentle arpeggiations that evoke starfields, deep space, and digital dreams. Include field recordings, micro-sounds, and a sense of infinite expansion.",
        "style": "ambient, electronica, ethereal, cosmic, evolving, textured",
        "tags": ["ambient", "electronica", "ethereal", "cosmic", "evolving", "textured", "digital"],
        "bpm": 70,
        "duration": "6:00",
        "instrumental": True,
        "difficulty": "advanced",
        "popularity": 85,
        "author": "System",
        "created_at": "2024-01-24",
        "updated_at": "2024-01-24",
        "example_image_url": "https://images.unsplash.com/photo-1545389336-cf09028c9b04?w=400&h=300&fit=crop",
        "metadata": {"model": "V5", "temperature": 0.8, "top_p": 0.97, "presence_penalty": 0.05, "frequency_penalty": 0.05}
    },
    {
        "id": "template_015",
        "name": "Afrobeats Celebration",
        "description": "Vibrant Afrobeats with West African rhythms and celebratory energy",
        "category": "afrobeats",
        "subcategory": "afrofusion",
        "prompt": "A vibrant Afrobeats track with West African rhythms, celebratory energy, and infectious melodies. Create a sun-drenched soundscape with complex percussion patterns, call-and-response vocals, and joyful instrumentation. The track should make people dance with its polyrhythmic grooves, bright guitar lines, and uplifting horn sections. Include traditional elements like talking drums blended with modern production for a global dancefloor sound.",
        "style": "afrobeats, vibrant, celebratory, rhythmic, joyful, fusion",
        "tags": ["afrobeats", "vibrant", "celebratory", "rhythmic", "joyful", "fusion", "african"],
        "bpm": 110,
        "duration": "3:45",
        "instrumental": False,
        "difficulty": "intermediate",
        "popularity": 90,
        "author": "System",
        "created_at": "2024-01-24",
        "updated_at": "2024-01-24",
        "example_image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop",
        "metadata": {"model": "V5", "temperature": 0.8, "top_p": 0.95, "presence_penalty": 0.1, "frequency_penalty": 0.1}
    },
    {
        "id": "template_016",
        "name": "Neo-Soul Revival",
        "description": "Warm neo-soul with vintage textures and emotional depth",
        "category": "neo-soul",
        "subcategory": "soul",
        "prompt": "A warm neo-soul track with vintage textures, emotional depth, and live instrumentation. Create a sound that bridges 70s soul nostalgia with modern songwriting. The track should feature warm Rhodes piano, wah-wah guitar, upright bass, and intimate vocals about love, introspection, and social consciousness. Include subtle jazz harmonies, hip-hop influenced drums, and a sense of organic authenticity.",
        "style": "neo-soul, warm, vintage, emotional, live, introspective",
        "tags": ["neo-soul", "warm", "vintage", "emotional", "live", "introspective", "soul"],
        "bpm": 92,
        "duration": "4:20",
        "instrumental": False,
        "difficulty": "advanced",
        "popularity": 88,
        "author": "System",
        "created_at": "2024-01-24",
        "updated_at": "2024-01-24",
        "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
        "metadata": {"model": "V5", "temperature": 0.8, "top_p": 0.95, "presence_penalty": 0.1, "frequency_penalty": 0.1}
    },
    {
        "id": "template_017",
        "name": "Drum & Bass Rush",
        "description": "High-energy drum & bass with breakbeats and sub-bass",
        "category": "drum-bass",
        "subcategory": "jungle",
        "prompt": "A high-energy drum & bass track with breakbeats, sub-bass, and frenetic energy. Create a relentless rhythm section with complex drum programming, rolling basslines, and atmospheric pads. The track should feature rapid-fire breaks, halftime drops, and a sense of controlled chaos. Include amen breaks, Reese bass, and neurofunk-inspired sound design for a modern D&B sound that works on dancefloors and headphones alike.",
        "style": "drum & bass, high-energy, breakbeats, sub-bass, atmospheric, frenetic",
        "tags": ["drum-bass", "high-energy", "breakbeats", "sub-bass", "atmospheric", "frenetic", "jungle"],
        "bpm": 174,
        "duration": "4:05",
        "instrumental": True,
        "difficulty": "advanced",
        "popularity": 86,
        "author": "System",
        "created_at": "2024-01-24",
        "updated_at": "2024-01-24",
        "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
        "metadata": {"model": "V5", "temperature": 0.8, "top_p": 0.95, "presence_penalty": 0.1, "frequency_penalty": 0.1}
    },
    {
        "id": "template_018",
        "name": "Reggaetón Flow",
        "description": "Modern reggaetón with dembow rhythm and Latin urban swagger",
        "category": "reggaeton",
        "subcategory": "urban",
        "prompt": "A modern reggaetón track with dembow rhythm, Latin urban swagger, and catchy hooks. Create a club-ready sound with the iconic 'dum-dum-dum' kick pattern, syncopated percussion, and melodic synth lines. The track should feature Spanish-language vocals about romance, nightlife, and confidence. Include dembow variations, reggaetón ad-libs, and a production style that bridges traditional Latin rhythms with contemporary trap influences.",
        "style": "reggaetón, dembow, Latin, urban, club, catchy",
        "tags": ["reggaeton", "dembow", "latin", "urban", "club", "catchy", "spanish"],
        "bpm": 95,
        "duration": "3:30",
        "instrumental": False,
        "difficulty": "intermediate",
        "popularity": 92,
        "author": "System",
        "created_at": "2024-01-24",
        "updated_at": "2024-01-24",
        "example_image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop",
        "metadata": {"model": "V5", "temperature": 0.8, "top_p": 0.95, "presence_penalty": 0.1, "frequency_penalty": 0.1}
    },
    {
        "id": "template_019",
        "name": "Phonk Drive",
        "description": "Memphis-inspired phonk with chopped samples and heavy bass",
        "category": "phonk",
        "subcategory": "memphis",
        "prompt": "A Memphis-inspired phonk track with chopped samples, heavy bass, and lo-fi aesthetics. Create a gritty, nostalgic sound that blends 90s hip-hop samples with modern trap production. The track should feature slowed-down vocal chops, distorted 808s, and eerie melodies. Include cowbell hits, vinyl crackle, and a sense of underground rawness that appeals to drift culture and sample-based music enthusiasts.",
        "style": "phonk, memphis, chopped, heavy bass, lo-fi, gritty",
        "tags": ["phonk", "memphis", "chopped", "heavy bass", "lo-fi", "gritty", "sample"],
        "bpm": 140,
        "duration": "2:45",
        "instrumental": True,
        "difficulty": "intermediate",
        "popularity": 88,
        "author": "System",
        "created_at": "2024-01-24",
        "updated_at": "2024-01-24",
        "example_image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop",
        "metadata": {"model": "V5", "temperature": 0.8, "top_p": 0.95, "presence_penalty": 0.1, "frequency_penalty": 0.1}
    },
    {
        "id": "template_020",
        "name": "K-Pop Banger",
        "description": "Polished K-pop with catchy hooks and high-production values",
        "category": "k-pop",
        "subcategory": "idol",
        "prompt": "A polished K-pop track with catchy hooks, high-production values, and idol-ready energy. Create a blend of electronic pop, hip-hop, and R&B that showcases vocal versatility and tight production. The track should feature a memorable chorus, rap verses, and a bridge that builds emotional tension. Include synth stabs, layered harmonies, and a production style that feels both futuristic and commercially accessible for global audiences.",
        "style": "k-pop, polished, catchy, high-production, idol, energetic",
        "tags": ["k-pop", "polished", "catchy", "high-production", "idol", "energetic", "pop"],
        "bpm": 128,
        "duration": "3:20",
        "instrumental": False,
        "difficulty": "advanced",
        "popularity": 93,
        "author": "System",
        "created_at": "2024-01-24",
        "updated_at": "2024-01-24",
        "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
        "metadata": {"model": "V5", "temperature": 0.8, "top_p": 0.95, "presence_penalty": 0.1, "frequency_penalty": 0.1}
    },
    {
        "id": "template_021",
        "name": "Trap Metal Aggression",
        "description": "Aggressive trap metal with distorted vocals and industrial beats",
        "category": "trap-metal",
        "subcategory": "industrial",
        "prompt": "An aggressive trap metal track with distorted vocals, industrial beats, and chaotic energy. Create a fusion of trap rhythms with metal guitar riffs, screamed vocals, and electronic breakdowns. The track should feature heavy 808s, blast beats, and a sense of controlled aggression. Include guitar chugs, vocal fry, and production techniques that bridge hip-hop and metal for a sound that's both brutal and rhythmic.",
        "style": "trap-metal, aggressive, distorted, industrial, chaotic, heavy",
        "tags": ["trap-metal", "aggressive", "distorted", "industrial", "chaotic", "heavy", "fusion"],
        "bpm": 150,
        "duration": "3:10",
        "instrumental": False,
        "difficulty": "advanced",
        "popularity": 84,
        "author": "System",
        "created_at": "2024-01-24",
        "updated_at": "2024-01-24",
        "example_image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop",
        "metadata": {"model": "V5", "temperature": 0.8, "top_p": 0.95, "presence_penalty": 0.1, "frequency_penalty": 0.1}
    }
]

# Filter out templates that already exist
new_templates = [t for t in missing_templates if t['id'] not in existing_ids]
print(f"Adding {len(new_templates)} new templates: {[t['id'] for t in new_templates]}")

# Append to existing templates
data['templates'].extend(new_templates)

# Write back
with open('app/static/templates/templates_complete.json', 'w') as f:
    json.dump(data, f, indent=2)

print(f"Total templates after addition: {len(data['templates'])}")
print("Done.")