name: app_prod

services:
  # REVERSE PROXY (Caddy) - Only use if NOT running Caddy via systemd
  # Start explicitly: docker compose -f compose.prod.yml --profile proxy up -d proxy
  proxy:
    image: caddy:2.7.6-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:2019/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    profiles:
      - proxy

  # PRODUCTION API BACKEND
  api:
    image: ${REGISTRY:-ghcr.io}/${REPO_OWNER:-owner}/${REPO_NAME:-app}/api:${IMAGE_TAG:?IMAGE_TAG is required}
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    networks:
      proxy_net:
        aliases:
          - prod_app
      default:
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 256M

  # DATABASE MIGRATIONS (Prod)
  migrate:
    image: ${REGISTRY:-ghcr.io}/${REPO_OWNER:-owner}/${REPO_NAME:-app}/api:${IMAGE_TAG:?IMAGE_TAG is required}
    command: ["alembic", "upgrade", "head"]
    env_file:
      - .env.prod
    networks:
      - default
    profiles:
      - migrate

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy_net:
    external: true
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16