name: app_staging

services:
  # STAGING API BACKEND
  api:
    image: ${REGISTRY:-ghcr.io}/${REPO_OWNER:-owner}/${REPO_NAME:-app}/api:${IMAGE_TAG:?IMAGE_TAG is required}
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - .env.staging
    environment:
      - WORKERS=2
    networks:
      proxy_net:
        aliases:
          - staging_app
      default:
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 768M
        reservations:
          cpus: '0.1'
          memory: 256M

  # DATABASE MIGRATIONS (Staging)
  migrate:
    image: ${REGISTRY:-ghcr.io}/${REPO_OWNER:-owner}/${REPO_NAME:-app}/api:${IMAGE_TAG:?IMAGE_TAG is required}
    command: ["alembic", "upgrade", "head"]
    env_file:
      - .env.staging
    networks:
      - default
    profiles:
      - migrate

networks:
  proxy_net:
    external: true
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
