import json
import os

# First, read the existing templates from templates.json
try:
    with open('app/static/templates/templates.json', 'r') as f:
        data = json.load(f)
        existing_templates = data.get('templates', [])
    print(f"Loaded {len(existing_templates)} existing templates from templates.json")
except Exception as e:
    print(f"Error loading templates.json: {e}")
    # Create minimal fallback
    existing_templates = [
        {
            'id': 'template_001',
            'name': 'Cyberpunk Synthwave',
            'description': 'A cyberpunk synthwave track',
            'category': 'electronic',
            'subcategory': 'synthwave',
            'prompt': 'A cyberpunk synthwave track',
            'style': 'synthwave, cyberpunk',
            'tags': ['electronic', 'synth'],
            'bpm': 120,
            'duration': '3:15',
            'instrumental': True,
            'difficulty': 'beginner',
            'popularity': 95,
            'author': 'System',
            'created_at': '2024-01-12',
            'updated_at': '2024-01-12',
            'example_image_url': 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop',
            'metadata': {'model': 'V5', 'temperature': 0.8, 'top_p': 0.95, 'presence_penalty': 0.1, 'frequency_penalty': 0.1}
        }
    ]

# Create the 10 new templates
new_templates = [
    {
        'id': 'template_012',
        'name': 'Hyperpop Glitchcore',
        'description': 'Maximalist hyperpop with glitch effects and digital chaos',
        'category': 'hyperpop',
        'subcategory': 'glitch',
        'prompt': 'A hyperpop track featuring glitch effects, digital chaos, and maximalist production. Create a sonic landscape of distorted vocals, crushed drums, and rainbow-bright synthesizers. The track should embody internet culture with TikTok-ready hooks, aggressive autotune, and chaotic breakdowns. Include hyper-compressed drums, pitch-shifted vocals, and video game sound effects that create a sense of digital overload and euphoric confusion.',
        'style': 'hyperpop, glitch, digital, chaotic, maximalist, bright',
        'tags': ['hyperpop', 'glitch', 'digital', 'chaotic', 'maximalist', 'bright', 'internet'],
        'bpm': 160,
        'duration': '2:30',
        'instrumental': False,
        'difficulty': 'intermediate',
        'popularity': 89,
        'author': 'System',
        'created_at': '2024-01-24',
        'updated_at': '2024-01-24',
        'example_image_url': 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop',
        'metadata': {'model': 'V5', 'temperature': 0.9, 'top_p': 0.95, 'presence_penalty': 0.2, 'frequency_penalty': 0.1}
    },
    {
        'id': 'template_013',
        'name': 'Drill Atmosphere',
        'description': 'Gritty UK drill with dark atmospheres and menacing bass',
        'category': 'drill',
        'subcategory': 'uk',
        'prompt': 'A UK drill track with dark atmospheres, menacing 808 bass, and gritty realism. Create a cold, urban soundscape with sparse percussion, haunting melodies, and aggressive vocal delivery. The track should evoke late-night city streets, tension, and survival mentality. Include sliding 808s, trap-style hi-hats, and atmospheric pads that create a sense of unease and raw energy.',
        'style': 'drill, dark, gritty, atmospheric, menacing, urban',
        'tags': ['drill', 'dark', 'gritty', 'atmospheric', 'menacing', 'urban', 'uk'],
        'bpm': 140,
        'duration': '3:15',
        'instrumental': True,
        'difficulty': 'intermediate',
        'popularity': 87,
        'author': 'System',
        'created_at': '2024-01-24',
        'updated_at': '2024-01-24',
        'example_image_url': 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop',
        'metadata': {'model': 'V5', 'temperature': 0.7, 'top_p': 0.9, 'presence_penalty': 0.1, 'frequency_penalty': 0.1}
    },
    {
        'id': 'template_014',
        'name': 'Ambient Electronica',
        'description': 'Ethereal ambient electronica with evolving textures and cosmic atmospheres',
        'category': 'ambient',
        'subcategory': 'electronica',
        'prompt': 'An ambient electronica track with evolving textures, cosmic atmospheres, and subtle rhythmic pulses. Create a meditative yet digital soundscape that bridges organic warmth with synthetic precision. The track should feature slowly morphing pads, granular synthesis, and gentle arpeggiations that evoke starfields, deep space, and digital dreams. Include field recordings, micro-sounds, and a sense of infinite expansion.',
        'style': 'ambient, electronica, ethereal, cosmic, evolving, textured',
        'tags': ['ambient', 'electronica', 'ethereal', 'cosmic', 'evolving', 'textured', 'digital'],
        'bpm': 70,
        'duration': '6:00',
        'instrumental': True,
        'difficulty': 'advanced',
        'popularity': 85,
        'author': 'System',
        'created_at': '2024-01-24',
        'updated_at': '2024-01-24',
        'example_image_url': 'https://images.unsplash.com/photo-1545389336-cf09028c9b04?w=400&h=300&fit=crop',
        'metadata': {'model': 'V5', 'temperature': 0.8, 'top_p': 0.97, 'presence_penalty': 0.05, 'frequency_penalty': 0.05}
    },
    {
        'id': 'template_015',
        'name': 'Afrobeats Celebration',
        'description': 'Vibrant Afrobeats with West African rhythms and celebratory energy',
        'category': 'afrobeats',
        'subcategory': 'afrofusion',
        'prompt': 'A vibrant Afrobeats track with West African rhythms, celebratory energy, and infectious melodies. Create a sun-drenched soundscape with complex percussion patterns, call-and-response vocals, and joyful instrumentation. The track should make people dance with its polyrhythmic grooves, bright guitar lines, and uplifting horn sections. Include traditional elements like talking drums blended with modern production for a global dancefloor sound.',
        'style': 'afrobeats, vibrant, celebratory, rhythmic, joyful, fusion',
        'tags': ['afrobeats', 'vibrant', 'celebratory', 'rhythmic', 'joyful', 'fusion', 'african'],
        'bpm': 110,
        'duration': '3:45',
        'instrumental': False,
        'difficulty': 'intermediate',
        'popularity': 90,
        'author': 'System',
        'created_at': '2024-01-24',
        'updated_at': '2024-01-24',
        'example_image_url': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop',
        'metadata': {'model': 'V5', 'temperature': 0.8, 'top_p': 0.95, 'presence_penalty': 0.1, 'frequency_penalty': 0.1}
    },
    {
        'id': 'template_016',
        'name': 'Neo-Soul Revival',
        'description': 'Warm neo-soul with vintage textures and emotional depth',
        'category': 'neo-soul',
        'subcategory': 'soul',
        'prompt': 'A warm neo-soul track with vintage textures, emotional depth, and live instrumentation. Create a sound that bridges 70s soul nostalgia with modern songwriting. The track should feature warm Rhodes piano, wah-wah guitar, upright bass, and intimate vocals about love, introspection, and social consciousness. Include subtle jazz harmonies, hip-hop influenced drums, and a sense of organic authenticity.',
        'style': 'neo-soul, warm, vintage, emotional, live, introspective',
        'tags': ['neo-soul', 'warm', 'vintage', 'emotional', 'live', 'introspective', 'soul'],
        'bpm': 92,
        'duration': '4:20',
        'instrumental': False,
        'difficulty': 'advanced',
        'popularity': 88,
        'author': 'System',
        'created_at': '2024-01-24',
        'updated_at': '2024-01-24',
        'example_image_url': 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=300&fit=crop',
        'metadata': {'model': 'V5', 'temperature': 0.75, 'top_p': 0.95, 'presence_penalty': 0.1, 'frequency_penalty': 0.1}
    },
    {
        'id': 'template_017',
        'name': 'Drum & Bass Frenzy',
        'description': 'High-energy drum & bass with breakbeats and futuristic sound design',
        'category': 'drum-bass',
        'subcategory': 'neurofunk',
        'prompt': 'A high-energy drum & bass track with complex breakbeats, futuristic sound design, and relentless energy. Create a sonic assault of amen breaks, Reese basslines, and intricate percussion programming. The track should feature atmospheric intros that drop into frenetic junglist chaos, with evolving bass textures and syncopated rhythms. Include neurofunk influences, halftime breakdowns, and a sense of controlled chaos.',
        'style': 'drum & bass, high-energy, futuristic, complex, frenetic, neurofunk',
        'tags': ['drum & bass', 'high-energy', 'futuristic', 'complex', 'frenetic', 'neurofunk', 'breakbeat'],
        'bpm': 174,
        'duration': '4:30',
        'instrumental': True,
        'difficulty': 'advanced',
        'popularity': 86,
        'author': 'System',
        'created_at': '2024-01-24',
        'updated_at': '2024-01-24',
        'example_image_url': 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&h=300&fit=crop',
        'metadata': {'model': 'V5', 'temperature': 0.8, 'top_p': 0.95, 'presence_penalty': 0.15, 'frequency_penalty': 0.1}
    },
    {
        'id': 'template_018',
        'name': 'Reggaetón Heat',
        'description': 'Sensual reggaetón with tropical rhythms and summer vibes',
        'category': 'reggaeton',
        'subcategory': 'tropical',
        'prompt': 'A sensual reggaetón track with tropical rhythms, summer vibes, and infectious dembow patterns. Create a heat-filled soundscape with reggaetón\'s signature kick-clap percussion, melodic hooks, and Spanish-language vocals about romance, partying, and confidence. The track should feature synth melodies, atmospheric pads, and breakdowns that make it perfect for club play and summer playlists.',
        'style': 'reggaetón, sensual, tropical, summer, infectious, latin',
        'tags': ['reggaetón', 'sensual', 'tropical', 'summer', 'infectious', 'latin', 'dembow'],
        'bpm': 96,
        'duration': '3:30',
        'instrumental': False,
        'difficulty': 'intermediate',
        'popularity': 91,
        'author': 'System',
        'created_at': '2024-01-24',
        'updated_at': '2024-01-24',
        'example_image_url': 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop',
        'metadata': {'model': 'V5', 'temperature': 0.8, 'top_p': 0.95, 'presence_penalty': 0.1, 'frequency_penalty': 0.1}
    },
    {
        'id': 'template_019',
        'name': 'Phonk Wave',
        'description': 'Retro phonk with Memphis rap samples and vaporwave aesthetics',
        'category': 'phonk',
        'subcategory': 'memphis',
        'prompt': 'A retro phonk track with Memphis rap samples, vaporwave aesthetics, and slowed-down grooves. Create a nostalgic yet modern sound that blends 90s hip-hop samples with contemporary production techniques. The track should feature chopped and screwed vocals, heavy 808 bass, cowbell percussion, and hazy atmospheres. Include elements of drift phonk with aggressive basslines and hypnotic loops.',
        'style': 'phonk, retro, memphis, vaporwave, nostalgic, hypnotic',
        'tags': ['phonk', 'retro', 'memphis', 'vaporwave', 'nostalgic', 'hypnotic', 'drift'],
        'bpm': 150,
        'duration': '2:45',
        'instrumental': False,
        'difficulty': 'intermediate',
        'popularity': 89,
        'author': 'System',
        'created_at': '2024-01-24',
        'updated_at': '2024-01-24',
        'example_image_url': 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop',
        'metadata': {'model': 'V5', 'temperature': 0.85, 'top_p': 0.97, 'presence_penalty': 0.2, 'frequency_penalty': 0.15}
    },
    {
        'id': 'template_020',
        'name': 'K-Pop Future',
        'description': 'Futuristic K-pop with holographic production and idol aesthetics',
        'category': 'k-pop',
        'subcategory': 'idol',
        'prompt': 'A futuristic K-pop track with holographic production, idol aesthetics, and genre-blending innovation. Create a polished, high-energy sound that combines electronic, pop, and hip-hop elements with Korean-language vocals. The track should feature catchy hooks, intricate choreography-ready rhythms, and a sense of visual storytelling. Include vocal processing, synth stabs, and breakdowns that showcase both vocal and production prowess.',
        'style': 'k-pop, futuristic, holographic, polished, energetic, genre-blending',
        'tags': ['k-pop', 'futuristic', 'holographic', 'polished', 'energetic', 'genre-blending', 'idol'],
        'bpm': 128,
        'duration': '3:20',
        'instrumental': False,
        'difficulty': 'advanced',
        'popularity': 92,
        'author': 'System',
        'created_at': '2024-01-24',
        'updated_at': '2024-01-24',
        'example_image_url': 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&h=300&fit=crop',
        'metadata': {'model': 'V5', 'temperature': 0.8, 'top_p': 0.95, 'presence_penalty': 0.1, 'frequency_penalty': 0.1}
    },
    {
        'id': 'template_021',
        'name': 'Trap Metal Aggression',
        'description': 'Aggressive trap metal with industrial textures and occult themes',
        'category': 'trap-metal',
        'subcategory': 'industrial',
        'prompt': 'An aggressive trap metal track with industrial textures, occult themes, and brutal energy. Create a sound that merges trap\'s 808 aggression with metal\'s distortion and intensity. The track should feature screamed vocals, distorted bass, blast beats, and dark atmospheres. Include elements of nu-metal, industrial noise, and horrorcore aesthetics for a truly menacing sonic experience.',
        'style': 'trap metal, aggressive, industrial, occult, brutal, dark',
        'tags': ['trap metal', 'aggressive', 'industrial', 'occult', 'brutal', 'dark', 'nu-metal'],
        'bpm': 155,
        'duration': '3:10',
        'instrumental': False,
        'difficulty': 'advanced',
        'popularity': 84,
        'author': 'System',
        'created_at': '2024-01-24',
        'updated_at': '2024-01-24',
        'example_image_url': 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop',
        'metadata': {'model': 'V5', 'temperature': 0.9, 'top_p': 0.9, 'presence_penalty': 0.3, 'frequency_penalty':