import json

# Existing 11 templates (simplified to avoid truncation)
existing_templates = [
    {
      "id": "template_001",
      "name": "Cyberpunk Synthwave",
      "description": "A cyberpunk synthwave track with pulsating bass and nostalgic 80s atmosphere",
      "category": "electronic",
      "subcategory": "synthwave",
      "prompt": "A cyberpunk synthwave track with pulsating basslines, arpeggiated synthesizers, and nostalgic 80s atmosphere. Features driving rhythm, neon-lit cityscape vibes, emotional melodic hooks, and retro-futuristic sound design. The track should evoke feelings of nighttime city driving, rain-slicked streets reflecting neon signs, and a sense of melancholic futurism. Include atmospheric pads, sequenced arpeggios, and a memorable lead melody that tells a story of human connection in a digital world.",
      "style": "synthwave, cyberpunk, 80s, retro-futuristic, atmospheric, driving",
      "tags": ["electronic", "synth", "cyberpunk", "80s", "nostalgic", "driving", "atmospheric"],
      "bpm": 120,
      "duration": "3:15",
      "instrumental": True,
      "difficulty": "beginner",
      "popularity": 95,
      "author": "System",
      "created_at": "2024-01-12",
      "updated_at": "2024-01-12",
      "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
      "metadata": {
        "model": "V5",
        "temperature": 0.8,
        "top_p": 0.95,
        "presence_penalty": 0.1,
        "frequency_penalty": 0.1
      }
    },
    {
      "id": "template_002",
      "name": "Deep House Groove",
      "description": "Smooth deep house with soulful vocals and hypnotic rhythms",
      "category": "electronic",
      "subcategory": "house",
      "prompt": "A deep house track with smooth, hypnotic rhythms, warm basslines, and soulful vocal samples. Create a late-night club atmosphere with atmospheric pads, subtle percussion, and a building energy that maintains a chilled vibe throughout. The track should feature a four-on-the-floor beat, filtered chords, and emotional depth that evokes feelings of connection and movement. Include breakdowns with atmospheric elements and builds that lead to satisfying drops without being overpowering.",
      "style": "deep house, soulful, hypnotic, atmospheric, chilled, groovy",
      "tags": ["electronic", "house", "deep", "soulful", "atmospheric", "groovy", "chilled"],
      "bpm": 122,
      "duration": "4:20",
      "instrumental": False,
      "difficulty": "intermediate",
      "popularity": 88,
      "author": "System",
      "created_at": "2024-01-12",
      "updated_at": "2024-01-12",
      "example_image_url": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop",
      "metadata": {
        "model": "V5",
        "temperature": 0.8,
        "top_p": 0.95,
        "presence_penalty": 0.1,
        "frequency_penalty": 0.1
      }
    },
    {
      "id": "template_003",
      "name": "Lo-fi Study Beats",
      "description": "Chill lo-fi hip hop beats perfect for studying or relaxing",
      "category": "electronic",
      "subcategory": "lofi",
      "prompt": "A chill lo-fi hip hop beat with dusty vinyl crackle, relaxed drum patterns, and warm jazz samples. Create a cozy, nostalgic atmosphere perfect for studying, relaxing, or late-night contemplation. The track should feature simple but effective drum programming, melodic piano or guitar loops, and atmospheric textures like rain sounds or ambient noise. Maintain a laid-back vibe with subtle variations and a sense of comforting repetition that supports focus without being distracting.",
      "style": "lo-fi, chill, relaxed, nostalgic, atmospheric, jazzy",
      "tags": ["electronic", "lofi", "chill", "relaxed", "nostalgic", "study", "jazzy"],
      "bpm": 85,
      "duration": "2:30",
      "instrumental": True,
      "difficulty": "beginner",
      "popularity": 92,
      "author": "System",
      "created_at": "2024-01-12",
      "updated_at": "2024-01-12",
      "example_image_url": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=300&fit=crop",
      "metadata": {
        "model": "V5",
        "temperature": 0.8,
        "top_p": 0.95,
        "presence_penalty": 0.1,
        "frequency_penalty": 0.1
      }
    },
    {
      "id": "template_004",
      "name": "Calm Meditation",
      "description": "Soothing ambient music for meditation and relaxation",
      "category": "ambient",
      "subcategory": "meditation",
      "prompt": "A calming ambient track for meditation and relaxation, featuring gentle pads, subtle textures, and slowly evolving soundscapes. Create a sense of peace and stillness with minimal melodic movement, atmospheric drones, and natural sounds like gentle wind or water. The track should promote relaxation and mindfulness with a slow tempo, wide stereo field, and frequencies that encourage deep breathing and mental calm. Avoid sudden changes or dramatic elements, focusing instead on gradual evolution and harmonic warmth.",
      "style": "ambient, calming, meditative, atmospheric, peaceful, evolving",
      "tags": ["ambient", "meditation", "calming", "peaceful", "atmospheric", "relaxing"],
      "bpm": 60,
      "duration": "8:00",
      "instrumental": True,
      "difficulty": "beginner",
      "popularity": 90,
      "author": "System",
      "created_at": "2024-01-12",
      "updated_at": "2024-01-12",
      "example_image_url": "https://images.unsplash.com/photo-1545389336-cf09028c9b04?w=400&h=300&fit=crop",
      "metadata": {
        "model": "V5",
        "temperature": 0.8,
        "top_p": 0.95,
        "presence_penalty": 0.1,
        "frequency_penalty": 0.1
      }
    },
    {
      "id": "template_005",
      "name": "Epic Trailer Music",
      "description": "Powerful orchestral music for movie trailers and epic scenes",
      "category": "cinematic",
      "subcategory": "trailer",
      "prompt": "Epic trailer music featuring powerful orchestral arrangements, massive percussion, and building tension. Create a sense of grandeur and drama with full orchestra, choir, and modern hybrid elements. The track should follow classic trailer structure: mysterious opening, building tension, emotional middle section, and explosive finale. Include brass fanfares, string ostinatos, taiko drums, and cinematic sound design that evokes blockbuster movies, heroic journeys, and world-changing events.",
      "style": "epic, orchestral, cinematic, powerful, dramatic, trailer",
      "tags": ["cinematic", "orchestral", "epic", "dramatic", "trailer", "powerful"],
      "bpm": 130,
      "duration": "2:45",
      "instrumental": False,
      "difficulty": "advanced",
      "popularity": 93,
      "author": "System",
      "created_at": "2024-01-12",
      "updated_at": "2024-01-12",
      "example_image_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&h=300&fit=crop",
      "metadata": {
        "model": "V5",
        "temperature": 0.8,
        "top_p": 0.95,
        "presence_penalty": 0.1,
        "frequency_penalty": 0.1
      }
    },
    {
      "id": "template_006",
      "name": "Tropical House Summer",
      "description": "Sunny tropical house with steel drums and beach vibes",
      "category": "electronic",
      "subcategory": "tropical",
      "prompt": "A sunny tropical house track with steel drum melodies, beachy vibes, and uplifting energy. Create a summer vacation atmosphere with bright synths, relaxed rhythms, and feel-good vocals. The track should evoke images of palm trees, ocean waves, and sunset parties. Include tropical percussion, catchy hooks, and a breezy arrangement that makes listeners feel like they're on a tropical island getaway.",
      "style": "tropical, house, summer, beachy, uplifting, sunny",
      "tags": ["electronic", "tropical", "house", "summer", "beachy", "uplifting", "happy"],
      "bpm": 115,
      "duration": "3:30",
      "instrumental": False,
      "difficulty": "intermediate",
      "popularity": 87,
      "author": "System",
      "created_at": "2024-01-12",
      "updated_at": "2024-01-12",
      "example_image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop",
      "metadata": {
        "model": "V5",
        "temperature": 0.8,
        "top_p": 0.95,
        "presence_penalty": 0.1,
        "frequency_penalty": 0.1
      }
    },
    {
      "id": "template_007",
      "name": "Psychedelic Rock Journey",
      "description": "Mind-bending psychedelic rock with swirling guitars and trippy effects",
      "category": "rock",
      "subcategory": "psychedelic",
      "prompt": "A psychedelic rock journey featuring swirling guitar effects, hypnotic rhythms, and mind-expanding soundscapes. Create a trippy, immersive experience with phaser-drenched guitars, organ drones, and experimental textures. The track should evolve through different sections, taking listeners on a sonic adventure through altered states of consciousness. Include improvisational elements, stereo panning effects, and a sense of cosmic exploration.",
      "style": "psychedelic, rock, trippy, experimental, immersive, cosmic",
      "tags": ["rock", "psychedelic", "experimental", "trippy", "guitar", "immersive"],
      "bpm": 100,
      "duration": "6:45",
      "instrumental": True,
      "difficulty": "advanced",
      "popularity": 82,
      "author": "System",
      "created_at": "2024-01-12",
      "updated_at": "2024-01-12",
      "example_image_url": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&h=300&fit=crop",
      "metadata": {
        "model": "V5",
        "temperature": 0.8,
        "top_p": 0.95,
        "presence_penalty": 0.1,
        "frequency_penalty": 0.1
      }
    },
    {
      "id": "template_008",
      "name": "Jazz Club Trio",
      "description": "Intimate jazz trio performance with piano, bass, and drums",
      "category": "jazz",
      "subcategory": "trio",
      "prompt": "An intimate jazz trio performance featuring piano, upright bass, and drums. Create a smoky club atmosphere with sophisticated harmonies, walking basslines, and tasteful drumming. The track should feature a standard jazz form with solos for each instrument, showcasing musical conversation and improvisational skill. Include swing feel, bluesy inflections, and the warm, organic sound of acoustic instruments in a cozy venue.",
      "style": "jazz, acoustic, intimate, sophisticated, swinging, bluesy",
      "tags": ["jazz", "acoustic", "trio", "intimate", "sophisticated", "improvisation"],
      "bpm": 140,
      "duration": "5:20",
      "instrumental": True,
      "difficulty": "advanced",
      "popularity": 85,
      "author": "System",
      "created_at": "2024-01-12",
      "updated_at": "2024-01-12",
      "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
      "metadata": {
        "model": "V5",
        "temperature": 0.8,
        "top_p": 0.95,
        "presence_penalty": 0.1,
        "frequency_penalty": 0.1
      }
    },
    {
      "id": "template_009",
      "name": "Future Bass Drop",
      "description": "Emotional future bass with huge drops and melodic supersaws",
      "category": "electronic",
      "subcategory": "futurebass",
      "prompt": "An emotional future bass track with huge drops, melodic supersaws, and heartfelt vocals. Create a balance between aggressive electronic production and emotional songwriting. The track should feature atmospheric verses, building tension, and explosive drops with intricate sound design. Include pitch-bent synths, vocal chops, and a sense of youthful energy mixed with melancholic beauty.",
      "style": "future bass, emotional, melodic, aggressive, atmospheric, drop",
      "tags": ["electronic", "future bass", "emotional", "melodic", "drop", "energetic"],
      "bpm": 150,
      "duration": "3:45",
      "instrumental": False,
      "difficulty": "intermediate",
      "popularity": 91,
      "author": "System",
      "created_at": "2024-01-12",
      "updated_at": "2024-01-12",
      "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
      "metadata": {
        "model": "V5",
        "temperature": 0.8,
        "top_p": 0.95,
        "presence_penalty": 0.1,
        "frequency_penalty": 0.1
      }
    },
    {
      "id": "template_010",
      "name": "Classical Piano Sonata",
      "description": "Elegant classical piano composition in sonata form",
      "category": "classical",
      "subcategory": "piano",
      "prompt": "An elegant classical piano sonata following traditional form and structure. Create a composition with clear thematic development, contrasting sections, and technical artistry. The track should demonstrate proper voice leading, harmonic progression, and dynamic expression. Include a memorable main theme, development section exploring different keys and textures, and a satisfying recapitulation. Capture the refined beauty of classical piano music with emotional depth and technical precision.",
      "style": "classical, piano, elegant, sophisticated, technical, emotional",
      "tags": ["classical", "piano", "elegant", "sophisticated", "technical", "emotional"],
      "bpm": 100,
      "duration": "7:30",
      "instrumental": True,
      "difficulty": "advanced",
      "popularity": 84,
      "author": "System",
      "created_at": "2024-01-12",
      "updated_at": "2024-01-12",
      "example_image_url": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=300&fit=crop",
      "metadata": {
        "model": "V5",
        "temperature": 0.8,
        "top_p": 0.95,
        "presence_penalty": 0.1,
        "frequency_penalty": 0.1
      }
    },
    {
      "id": "template_011",
      "name": "Reggae Sunshine",
      "description": "Chilled reggae with positive vibes and laid-back groove",
      "category": "reggae",
      "subcategory": "roots",
      "prompt": "A chilled reggae track with positive vibes, laid-back groove, and uplifting message. Create a sunny, relaxed atmosphere with off-beat guitar chops, walking basslines, and steady one-drop drum pattern. The track should feature soulful vocals about unity, love, and social consciousness. Include horn stabs, organ skanks, and that unmistakable reggae bounce that makes people sway and smile.",
      "style": "reggae, chilled, positive, laid-back, sunny, roots",
      "tags": ["reggae", "chilled", "positive", "laid-back", "sunny", "roots"],
      "bpm": 80,
      "duration": "4:10",
      "instrumental": False,
      "difficulty": "intermediate",
      "popularity": 86,
      "author": "System",
      "created_at": "2024-01-12",
      "updated_at": "2024-01-12",
