"""Add soft delete to users

Revision ID: bfe4ed93bead
Revises: a2bfb2722862
Create Date: 2026-02-08 15:46:11.019766

"""

from alembic import op
import sqlalchemy as sa
import app.models



# revision identifiers, used by Alembic.
revision = 'bfe4ed93bead'
down_revision = 'a2bfb2722862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=200), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'event_id', name='uq_webhook_source_event_id')
    )
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('user_id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('active_model_version_id', app.models.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_user_id'), 'voice_profiles', ['user_id'], unique=False)
    op.create_table('voice_dataset_files',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('voice_profile_id', app.models.GUID(), nullable=False),
    sa.Column('r2_key', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_dataset_files_voice_profile_id'), 'voice_dataset_files', ['voice_profile_id'], unique=False)
    op.create_table('voice_training_jobs',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('user_id', app.models.GUID(), nullable=False),
    sa.Column('voice_profile_id', app.models.GUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('modal_call_id', sa.String(length=200), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_training_jobs_user_id'), 'voice_training_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_voice_training_jobs_voice_profile_id'), 'voice_training_jobs', ['voice_profile_id'], unique=False)
    op.create_table('voice_model_versions',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('voice_profile_id', app.models.GUID(), nullable=False),
    sa.Column('training_job_id', app.models.GUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('r2_model_key', sa.Text(), nullable=True),
    sa.Column('r2_config_key', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['training_job_id'], ['voice_training_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_model_versions_training_job_id'), 'voice_model_versions', ['training_job_id'], unique=False)
    op.create_index(op.f('ix_voice_model_versions_voice_profile_id'), 'voice_model_versions', ['voice_profile_id'], unique=False)
    op.create_table('voice_conversion_jobs',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('user_id', app.models.GUID(), nullable=False),
    sa.Column('voice_profile_id', app.models.GUID(), nullable=False),
    sa.Column('model_version_id', app.models.GUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('modal_call_id', sa.String(length=200), nullable=True),
    sa.Column('input_r2_key', sa.Text(), nullable=True),
    sa.Column('output_r2_key', sa.Text(), nullable=True),
    sa.Column('input_duration_sec', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['voice_model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_conversion_jobs_model_version_id'), 'voice_conversion_jobs', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_voice_conversion_jobs_user_id'), 'voice_conversion_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_voice_conversion_jobs_voice_profile_id'), 'voice_conversion_jobs', ['voice_profile_id'], unique=False)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_index(op.f('ix_voice_conversion_jobs_voice_profile_id'), table_name='voice_conversion_jobs')
    op.drop_index(op.f('ix_voice_conversion_jobs_user_id'), table_name='voice_conversion_jobs')
    op.drop_index(op.f('ix_voice_conversion_jobs_model_version_id'), table_name='voice_conversion_jobs')
    op.drop_table('voice_conversion_jobs')
    op.drop_index(op.f('ix_voice_model_versions_voice_profile_id'), table_name='voice_model_versions')
    op.drop_index(op.f('ix_voice_model_versions_training_job_id'), table_name='voice_model_versions')
    op.drop_table('voice_model_versions')
    op.drop_index(op.f('ix_voice_training_jobs_voice_profile_id'), table_name='voice_training_jobs')
    op.drop_index(op.f('ix_voice_training_jobs_user_id'), table_name='voice_training_jobs')
    op.drop_table('voice_training_jobs')
    op.drop_index(op.f('ix_voice_dataset_files_voice_profile_id'), table_name='voice_dataset_files')
    op.drop_table('voice_dataset_files')
    op.drop_index(op.f('ix_voice_profiles_user_id'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
